language: c

env:
   global:
     - VERBOSE: 1

os: linux
dist: xenial

jobs:
   include:
     - os: linux
       env: USE_ASAN=ON CONFIG=Debug
     - os: linux
       env: USE_ASAN=OFF CONFIG=Release
     - os: windows
       env: CONFIG=Release	

install:
  - ./useful_files/travis/$TRAVIS_OS_NAME.install.sh

script:
   - ./useful_files/travis/$TRAVIS_OS_NAME.sh

before_deploy:
  - ./useful_files/travis/$TRAVIS_OS_NAME.before_deploy.sh

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: libsurvive-$TRAVIS_TAG-$TRAVIS_OS_NAME.7z
    skip_cleanup: true
    on:
      branch: master
      condition: $CONFIG=Release
      tags: true

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    