language: c

matrix:
   include:
      - os: linux
      - os: windows

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential zlib1g-dev libx11-dev libusb-1.0-0-dev freeglut3-dev liblapacke-dev libopenblas-dev libatlas-base-dev

script:
   - mkdir -p bin
   - cd bin && cmake .. && cmake --build .
