language: c

matrix:
   include:
      - os: linux
      - os: windows

before_install:
  - if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; then sudo apt-get install build-essential zlib1g-dev libx11-dev libusb-1.0-0-dev freeglut3-dev liblapacke-dev libopenblas-dev libatlas-base-dev libpcap-dev; fi   

script:
   - mkdir -p bin
   - cd bin
   - cmake -DENABLE_TESTS=ON -DUSE_ASAN=ON ..
   - cmake --build .
   - ctest . -C Debug --output-on-failure
