# This is a basic workflow to help you get started with Actions

name: Build Wheels

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  create:
    tags: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: satackey/action-docker-layer-caching@v0.0.8
        if: runner.os != 'Windows'
          
      - name: Build the Docker image
        working-directory: ${{runner.workspace}}/libsurvive/useful_files
        if: runner.os != 'Windows'
        run: docker build . -f ./Docker.centos --tag libsurvive_manylinux2014_x86_64

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels - Linux
        if: runner.os != 'Windows'
        run: python -m cibuildwheel
        env:
          CIBW_ENVIRONMENT: LD_LIBRARY_PATH=/opt/rh/devtoolset-9/root/usr/lib64:/opt/rh/devtoolset-9/root/usr/lib:/opt/rh/devtoolset-9/root/usr/lib64/dyninst:/opt/rh/devtoolset-9/root/usr/lib/dyninst:/usr/local/lib64:/usr/local/lib:/usr/local/lib/libsurvive/plugins
          CIBW_BEFORE_BUILD: rm -rf /project/bin && make install
          CIBW_BUILD_VERBOSITY: 3
          CIBW_MANYLINUX_X86_64_IMAGE: libsurvive_manylinux2014_x86_64
          CIBW_BUILD: cp3*manylinux_x86_64
      - name: Build wheels - Windows
        if: runner.os == 'Windows'
        run: python -m cibuildwheel
        env:
          CIBW_BUILD_VERBOSITY: 3
          CIBW_BUILD: cp3*win*64

      - uses: actions/upload-artifact@v2
        name: Upload
        with:
          path: ${{runner.workspace}}/libsurvive/wheelhouse/*.whl
